using System.ComponentModel;

namespace PalmHill.BlazorChat.Shared.Models
{
    /// <summary>
    /// Represents a chat message in a conversation.
    /// </summary>
    public class ChatMessage
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Gets or sets the role of the entity that generated the message.
        /// </summary>
        /// <value>
        /// The role of the entity that generated the message.
        /// </value>
        [DefaultValue(ChatMessageRole.User)]
        public ChatMessageRole? Role { get; set; }

        /// <summary>
        /// Gets or sets the content of the message.
        /// </summary>
        /// <value>
        /// The content of the message.
        /// </value>
        [DefaultValue("What are cats?")]
        public string? Message { get; set; }

        /// <summary>
        /// The user can add attachments to the message, the attachment will becom part of the context.
        /// </summary>
        public List<string> AttachmentIds { get; set; } = new List<string>();
    }

    /// <summary>
    /// Represents the role of the entity that generated a chat message.
    /// </summary>
    public enum ChatMessageRole
    {
        /// <summary>
        /// Represents a message generated by an assistant.
        /// </summary>
        [Description("Assistant Message")]
        Assistant = 0,

        /// <summary>
        /// Represents a message generated by a user.
        /// </summary>
        [Description("User Message")]
        User = 1,

        [Description("User Message")]
        Question = 2,
    }
}